a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
i = float(input("Masukkan nilai i: "))
j = float(input("Masukkan nilai j: "))
x = float(input("Masukkan nilai x: "))
y = float(input("Masukkan nilai y: "))
hasil = (a - b) * (i / j) - (x + y)
print(f"Hasil: {hasil:.3f}")