Nama = input("Nama\t\t\t: ")
Nim = input("NIM\t\t\t: ")
Kelas = input("Kelas Paralel\t\t: ")
Ttl = input("Tempat/Tanggal Lahir\t: ")
Alamat = input("Alamat\t\t\t: ")
Hobby = input("Hobby\t\t\t: ")
NoHp = input("No. HP\t\t\t: ")

print("\nOutput")
print(f"Nama\t\t\t: {Nama}")
print(f"NIM\t\t\t: {Nim}")
print(f"Kelas Paralel\t\t: {Kelas}")
print(f"Tempat/Tanggal Lahir\t: {Ttl}")
print(f"Alamat\t\t\t: {Alamat}")
print(f"Hobby\t\t\t: {Hobby}")
print(f"No. HP\t\t\t: {NoHp}")
